name: cucumber-eclipse plugin (1.x)

on:
  push:
    branches: [ v1.x ]
  pull_request:
    branches: [ v1.x ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: code
    - uses: actions/checkout@v2
      with:
        path: gh-pages
        ref: gh-pages
      if: github.event_name != 'pull_request'
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        architecture: 'x64'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
         ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file code/pom.xml

